version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "127.0.0.1:5431:5432"
    environment:
      POSTGRES_PASSWORD: dwh_password
      POSTGRES_USER: dwh_user
      POSTGRES_DB: dwh_immobilien_db
    volumes:
      - dwh-data:/var/lib/postgresql/data
  # Handle JS Pre-Rendering issue for site like Immowelt
  splash:
    image: scrapinghub/splash
    ports:
      - "127.0.0.1:8050:8050"

volumes:
  dwh-data: