version: '3.1'

services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_HOST}:${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - dwh-data:/var/lib/postgresql/data
  # Handle JS Pre-Rendering issue for site like Immowelt
  splash:
    image: scrapinghub/splash
    ports:
      - "127.0.0.1:8050:8050"

volumes:
  dwh-data: